// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using campeonato.Context;

namespace campeonato.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211006215204_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("campeonato.Entities.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("campeonato.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("integer");

                    b.Property<string>("Jogada")
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("campeonato.Entities.Jogo", b =>
                {
                    b.HasOne("campeonato.Entities.Campeonato", null)
                        .WithMany("Jogadas")
                        .HasForeignKey("CampeonatoId");
                });

            modelBuilder.Entity("campeonato.Entities.Campeonato", b =>
                {
                    b.Navigation("Jogadas");
                });
#pragma warning restore 612, 618
        }
    }
}
